// Generated by CoffeeScript 1.3.3
var expect, list;

expect = require('expect.js');

list = require('../lib/coll').list;

describe('list()', function() {
  return describe('list variable', function() {
    it('should be able to access items by index directly', function() {
      var ls;
      ls = list('asdf');
      expect(ls(0)).to.be('a');
      expect(ls(1)).to.be('s');
      expect(ls(2)).to.be('d');
      return expect(ls(3)).to.be('f');
    });
    return it('should be able to set items by index directly', function() {
      var ls;
      ls = list('asdf');
      ls(1, 'z');
      ls(2, 'z');
      expect(ls(0)).to.be('a');
      expect(ls(1)).to.be('z');
      expect(ls(2)).to.be('z');
      return expect(ls(3)).to.be('f');
    });
  });
});
