// Generated by CoffeeScript 1.3.3
var List, expect;

expect = require('expect.js');

List = require('../lib/coll').List;

describe('List', function() {
  describe('Instance Properties', function() {
    return describe('length', function() {
      var ls;
      ls = null;
      beforeEach(function() {
        return ls = List();
      });
      it('should have an initial value of zero', function() {
        return expect(ls.length).to.be(0);
      });
      return it('should not be configurable', function() {
        delete ls.length;
        return expect(ls).to.have.property('length');
      });
    });
  });
  return describe('Unmodified methods borrowed from Array prototype', function() {
    expect(List.prototype.reverse).to.be.a(Function);
    return expect(List.prototype.join).to.be.a(Function);
  });
});
